package com.hotusm.model;

public class News {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.ID
     *
     * @mbggenerated Sat Sep 17 22:34:46 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.TITLE
     *
     * @mbggenerated Sat Sep 17 22:34:46 CST 2016
     */
    private String title;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.ID
     *
     * @return the value of news.ID
     *
     * @mbggenerated Sat Sep 17 22:34:46 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.ID
     *
     * @param id the value for news.ID
     *
     * @mbggenerated Sat Sep 17 22:34:46 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.TITLE
     *
     * @return the value of news.TITLE
     *
     * @mbggenerated Sat Sep 17 22:34:46 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.TITLE
     *
     * @param title the value for news.TITLE
     *
     * @mbggenerated Sat Sep 17 22:34:46 CST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }
}